repos:
- repo: local
  hooks:
  - id: export-requirements
    name: Export Requirements
    entry: poetry run python scripts/generate_requirements.py
    language: system
    files: ^pyproject\.toml$
    pass_filenames: false
